url: "https://berserker.technology"
baseurl: ""
title: "Berserker Technology"
description: >-
  Coming Spring 2020

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

include:
  - _redirects
  - robots.txt

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  style: compressed

jekyll-minifier:
  uglifier_args:
    harmony: true
