url: "https://berserker.technology" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Berserker Technology" # the name of your site, e.g. ACME Corp.

include: [_redirects]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  style: compressed

minify_html: true

plugins:
  - octopress-minify-html
