url: "https://berserker.technology" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Berserker Technology" # the name of your site, e.g. ACME Corp.
description: >-
  Coming Spring 2020

plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

include:
  - _redirects
  - robots.txt

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

sass:
  style: compressed

jekyll-minifier:
  uglifier_args:
    harmony: true
